apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: kubesphere-monitoring-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://github.com/sebihiy/kube-prometheus-stack
    targetRevision: main
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true

